spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spcha?autoReconnect=true&noDatetimeStringSync=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&useUnicode=true&mysqlEncoding=utf8&noAccessToProcedureBodies=true&serverTimezone=UTC
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create
    show-sql: true

  devtools:
    livereload:
      enabled: true